name: Compile Codebook
run-name: Compile codebook
on: [push]
jobs:
    compile:
        runs-on: ubuntu-latest
        container: ghcr.io/wiwiho/codebook:latest
        steps:
            - name: Checkout
              uses: actions/checkout@v3
            - name: Check unused files
              run: |
                chmod +x scripts/check_usage.sh
                scripts/check_usage.sh
            - name: Check indentations
              run: |
                chmod +x scripts/check_indent.sh
                scripts/check_indent.sh
            - name: Compile
              run: |
                texfot latexmk -xelatex main.tex
                cp main.pdf /root/ideograph_advantage_codebook.pdf
            - name: Checkout
              uses: actions/checkout@v3
              with:
                ref: build
            - name: Copy PDF
              run: cp /root/ideograph_advantage_codebook.pdf .
            - name: Commit
              uses: stefanzweifel/git-auto-commit-action@v4
              with:
                commit_message: build
                file_pattern: ideograph_advantage_codebook.pdf
