name: Compile Codebook
run-name: Compile codebook
on: [push]
jobs:
    compile:
        runs-on: ubuntu-latest
        container: ghcr.io/wiwiho/codebook:latest
        steps:
            - name: Checkout
              uses: actions/checkout@v3
            - name: Install font
              run: |
                chmod +x scripts/install_consolas.sh
                scripts/install_consolas.sh
            - name: Check unused files
              run: |
                chmod +x scripts/check_usage.sh
                scripts/check_usage.sh
            - name: Check indentations
              run: |
                chmod +x scripts/check_indent.sh
                scripts/check_indent.sh
            - name: Compile
              run: texfot latexmk -xelatex main.tex
#testing
