name: Compile Codebook
run-name: Compile codebook
on: [push]
jobs:
    compile:
        runs-on: ubuntu-latest
        steps:
            - name: Install packages
              run: apt install python3 texlive-full
            - name: Checkout
              uses: actions/checkout@v3
            - name: Check unused files
              run: scripts/check_usage.sh
            - name: Check indentations
              run: scripts/check_indent.sh
            - name: Compile
              run: texfot latexmk -xelatex main.tex
#testing
